### ISSUE TITLE
Code task: Level progression via email

### ISSUE THREAD

**Issue by AltVox** [UoSGamesGroups/first-semester-l4-5-group-15#36]
This task should take no more then 3 hours.

**Comment by CJace33** [comment]
1 hour, waiting on altered Emails

**Comment by CJace33** [comment]
30 minutes, started code for displaying Emails

**Comment by CJace33** [comment]
30 minutes, added new emails and some code, now need to do level progression before I can make them appear at the correct time.

**Comment by CJace33** [comment]
1 hour, made the emails disappear after X seconds
